version: '3.8'

services:
  goods-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/goods_service?sslmode=disable
      - REDIS_ADDR=redis:6379
      - NATS_ADDR=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats
      - clickhouse

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goods_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  nats:
    image: nats:2

  clickhouse:
    image: yandex/clickhouse-server:21
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  postgres_data:
  redis_data:
  clickhouse_data: